Product/Development/Progetto 1/Progetto 1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Product/Development/Progetto 1/Progetto 1/Controllers/SignupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using Progetto_1.Models;

namespace Progetto_1.Controllers
{
    public class SignupController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(IFormCollection collection)
        {
            User u = CollectionToUser(collection);
            return View("Index", u);
        }

        [HttpPost]
        public IActionResult DataCheck(IFormCollection collection)
        {
            if (ModelState.IsValid)
            {
                User u = CollectionToUser(collection);
                return View("DataCheck", u);
            }
            else
            {
                return View();
            }
        }

        private User CollectionToUser(IFormCollection collection)
        {
            collection.TryGetValue("FirstName", out StringValues fName);
            collection.TryGetValue("LastName", out StringValues lName);
            collection.TryGetValue("Birthday", out StringValues bDay);
            collection.TryGetValue("Address", out StringValues address);
            collection.TryGetValue("CivicNumber", out StringValues cNumber);
            collection.TryGetValue("City", out StringValues city);
            collection.TryGetValue("Nap", out StringValues nap);
            collection.TryGetValue("PhoneNumber", out StringValues phone);
            collection.TryGetValue("Email", out StringValues email);
            collection.TryGetValue("Gender", out StringValues gender);
            collection.TryGetValue("Hobby", out StringValues hobby);
            collection.TryGetValue("Job", out StringValues job);

            User u = new User()
            {
                FirstName = fName.FirstOrDefault(),
                LastName = lName.FirstOrDefault(),
                Address = address.FirstOrDefault(),
                CivicNumber = cNumber.FirstOrDefault(),
                City = city.FirstOrDefault(),
                PhoneNumber = phone.FirstOrDefault(),
                Email = email.FirstOrDefault(),
                Gender = gender.FirstOrDefault(),
                Hobby = hobby.FirstOrDefault(),
                Job = job.FirstOrDefault(),
            };

            DateTime bd = new DateTime();
            DateTime.TryParse(bDay.FirstOrDefault(), out bd);
            u.Birthday = bd;

            int np = new int();
            int.TryParse(nap.FirstOrDefault(), out np);
            u.Nap = np;
            return u;
        }

        [HttpPost]
        public IActionResult Save(IFormCollection collection)
        {
            User user = CollectionToUser(collection);
            try
            {
                DateTime dt = DateTime.Now;
                CSVHelper all = new CSVHelper("wwwroot/Registrazioni/Registrazioni_tutte.csv", ";", new string[] { "data", "nome", "cognome", "data_nascita", "via", "numero_civico", "citta", "nap", "telefono", "email", "sesso", "hobby", "professione" });
                CSVHelper day = new CSVHelper(string.Format("wwwroot/Registrazioni/Registrazioni_{0}_{1}_{2}.csv", dt.Year, dt.Month, dt.Day), ";", new string[] { "data", "nome", "cognome", "data_nascita", "via", "numero_civico", "citta", "nap", "telefono", "email", "sesso", "hobby", "professione" });
                string[] s = new string[]
                {
                    dt.ToString(),
                    user.FirstName,
                    user.LastName,
                    user.Birthday.ToString(),
                    user.Address,
                    user.CivicNumber,
                    user.City,
                    user.Nap.ToString(),
                    user.PhoneNumber,
                    user.Email,
                    user.Gender,
                    user.Hobby,
                    user.Job
                };
                all.Write(s);
                day.Write(s);

                return RedirectToAction("", "ReadCheck");
            }
            catch (Exception)
            {
                return View("Index");
            }
        }
    }
}

Product/Development/Progetto 1/Progetto 1/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>

<p>Ringrazio <a href="https://www.iconfinder.com/Makoto_msk">Mariano Tardon</a> per l’icona</p>
<p>
    Questo sito web permette la registrazione dei dati di un utente all'interno di due file .CSV.
    Quest'applicazione è stata progettata e realizzata interamente da <b>Matan Davidi</b>,
    studente alla Scuola Arti e Mestieri di Trevano, sezione informatica, terzo anno. <br />
    Copyright © 2018 Matan Davidi
</p>
<p>
    This program is free software: you can redistribute it and/or modify <br />
    it under the terms of the GNU General Public License as published by <br />
    the Free Software Foundation, either version 3 of the License, or <br />
    (at your option) any later version. <br />
    <br />
    This program is distributed in the hope that it will be useful, <br />
    but WITHOUT ANY WARRANTY; without even the implied warranty of <br />
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the <br />
    GNU General Public License for more details. <br />
    <br />
    You should have received a copy of the GNU General Public License <br />
    along with this program.  If not, see <a href="https://www.gnu.org/licenses/">https://www.gnu.org/licenses/</a>.
</p>

Product/Development/Progetto 1/Progetto 1/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contatti";
}
<h2>@ViewData["Title"]</h2>

<address>
    Potete contattarmi tramite <strong>email:</strong> <a href="mailto:davidi.matan@gmail.com">davidi.matan@gmail.com</a> <br />
    Guarda altri miei lavori sul mio <a href="http://samtinfo.ch/i16davmat/web">sito web</a>
</address>

Product/Development/Progetto 1/Progetto 1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
    <h1 class="text-center text-uppercase">Progetto 1</h1>
    <h2 class="text-center">Matan Davidi - 2018</h2>
    <p>Benvenuto all'applicazione web "Progetto 1"</p>
    <p>Questa applicazione permette di registrarsi all'interno di un file CSV</p>
    <p>Premi il pulsante in basso per registrarti</p>
    <input class="btn btn-block btn-default" type="submit" name="signup" value="Registrati" onclick="window.location.href='@Url.Action("", "Signup")';" />
</div>